Update dragen somatic tool to cater for --tumor-bam-input AND --bam-input
To resolve

> ERROR: Cannot enable map-align with multiple bam/cram inputs. Run map-align separately on each input and then run from multiple bam/cram inputs with map-align off

We run the map align steps first and then run the variant calling step.

This is only the case when --tumor-bam, --input-bam and --enable-map-align are set to true.